import json

with open('eda_analysis.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_cells = [
    # ── BÖLÜM 13 ─────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 🎮 Bölüm 13 — Komut Tipi Analizi (Transfer vs Dozaj)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "import matplotlib.gridspec as gridspec\n",
            "\n",
            "# Komut isimleri\n",
            "CMD_NAMES = {19:'KK Transfer', 20:'BK Transfer', 21:'KK Dozaj', 22:'BK Dozaj'}\n",
            "CMD_COLORS = {19:'#2196F3', 20:'#4CAF50', 21:'#FF9800', 22:'#E91E63'}\n",
            "\n",
            "# Komut dağılımı\n",
            "fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n",
            "for ax, df, title in [(axes[0], train, 'TRAIN'), (axes[1], test, 'TEST')]:\n",
            "    vc = df['commandno'].value_counts().sort_index()\n",
            "    colors = [CMD_COLORS.get(c, 'gray') for c in vc.index]\n",
            "    bars = ax.bar([CMD_NAMES.get(c, str(c)) for c in vc.index], vc.values, color=colors, alpha=0.85, edgecolor='white')\n",
            "    for bar, val in zip(bars, vc.values):\n",
            "        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+100, f'{val:,}',\n",
            "                ha='center', va='bottom', fontsize=10, fontweight='bold')\n",
            "    ax.set_title(f'{title} — Komut Dağılımı', fontweight='bold')\n",
            "    ax.set_ylabel('Satır Sayısı')\n",
            "plt.tight_layout()\n",
            "plt.savefig('command_distribution.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
            "print('Transfer (19,20) vs Dozaj (21,22):')\n",
            "for cmd in sorted(train['commandno'].unique()):\n",
            "    cnt = (train['commandno']==cmd).sum()\n",
            "    print(f'  Komut {cmd} ({CMD_NAMES.get(cmd,\"?\")}): {cnt:>10,} satır ({cnt/len(train)*100:.1f}%)')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# bk_level dağılımı komut tipine göre\n",
            "fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n",
            "axes = axes.flatten()\n",
            "for i, cmd in enumerate(sorted(train['commandno'].unique())):\n",
            "    ax = axes[i]\n",
            "    subset = train[train['commandno']==cmd]['bk_level'].dropna()\n",
            "    subset = subset[subset > 0]  # sıfır satırları çıkar\n",
            "    ax.hist(subset.sample(min(20000, len(subset)), random_state=42),\n",
            "            bins=80, color=CMD_COLORS.get(cmd,'gray'), alpha=0.85, edgecolor='white')\n",
            "    ax.axvline(subset.mean(), color='red', linestyle='--', linewidth=2,\n",
            "               label=f'Ort: {subset.mean():.2f}')\n",
            "    ax.set_title(f'Komut {cmd} — {CMD_NAMES.get(cmd,\"?\")} | bk_level Dağılımı', fontweight='bold')\n",
            "    ax.set_xlabel('bk_level')\n",
            "    ax.legend()\n",
            "plt.suptitle('Komut Tipine Göre bk_level Dağılımı', fontsize=15, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('bklevel_by_command.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Transfer vs Dozaj — ortalama proses profili\n",
            "# Bir prosesin göreceli süresi içinde bk_level nasıl değişiyor?\n",
            "import pandas as pd\n",
            "\n",
            "train['rel_time'] = (train['ts'] - train['starttime']).dt.total_seconds()\n",
            "train['proc_dur'] = (train['endtime'] - train['starttime']).dt.total_seconds()\n",
            "train['rel_pct']  = (train['rel_time'] / train['proc_dur'].replace(0, np.nan) * 100).clip(0, 100)\n",
            "\n",
            "fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n",
            "axes = axes.flatten()\n",
            "\n",
            "for i, cmd in enumerate(sorted(train['commandno'].unique())):\n",
            "    ax = axes[i]\n",
            "    subset = train[(train['commandno']==cmd) & (train['bk_level'] > 0)].copy()\n",
            "    # 100 bin'e böl, her bin için ortalama\n",
            "    subset['bin'] = pd.cut(subset['rel_pct'], bins=50, labels=False)\n",
            "    profile = subset.groupby('bin')['bk_level'].agg(['mean','std']).reset_index()\n",
            "    ax.plot(profile['bin']*2, profile['mean'], color=CMD_COLORS.get(cmd,'gray'), linewidth=2)\n",
            "    ax.fill_between(profile['bin']*2,\n",
            "                    profile['mean'] - profile['std'],\n",
            "                    profile['mean'] + profile['std'],\n",
            "                    alpha=0.2, color=CMD_COLORS.get(cmd,'gray'))\n",
            "    ax.set_title(f'Komut {cmd} — {CMD_NAMES.get(cmd,\"?\")}\\nProses İçi bk_level Profili', fontweight='bold')\n",
            "    ax.set_xlabel('Proses İçi İlerleme (%)')\n",
            "    ax.set_ylabel('bk_level (ort ± std)')\n",
            "    ax.grid(alpha=0.3)\n",
            "\n",
            "plt.suptitle('Komuta Göre bk_level Zaman Profili\\n(ortalama ± standart sapma)', fontsize=14, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('command_profile.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()"
        ]
    },

    # ── BÖLÜM 14 ─────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 🏭 Bölüm 14 — Makine × Komut Çapraz Analizi"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Makine × Komut pivot tablosu\n",
            "pivot = train.groupby(['machineid','commandno']).size().unstack(fill_value=0)\n",
            "pivot.columns = [CMD_NAMES.get(c, str(c)) for c in pivot.columns]\n",
            "print('=== Makine × Komut Satır Sayısı ===')\n",
            "print(pivot)\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(12, 5))\n",
            "bottom = np.zeros(len(pivot))\n",
            "cols = list(pivot.columns)\n",
            "bar_colors = ['#2196F3','#4CAF50','#FF9800','#E91E63']\n",
            "for j, col in enumerate(cols):\n",
            "    ax.bar(pivot.index.astype(str), pivot[col], bottom=bottom,\n",
            "           label=col, color=bar_colors[j % len(bar_colors)], alpha=0.85)\n",
            "    bottom += pivot[col].values\n",
            "ax.set_title('Makine × Komut Dağılımı (Stacked)', fontweight='bold')\n",
            "ax.set_xlabel('Machine ID')\n",
            "ax.set_ylabel('Satır Sayısı')\n",
            "ax.legend(loc='upper right')\n",
            "plt.tight_layout()\n",
            "plt.savefig('machine_command_cross.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
            "print('\\n⚠️  Makine 243 — BK Transfer (komut 20):', (train[(train.machineid==243)&(train.commandno==20)].shape[0]), 'satır (olmalı: 0!)')"
        ]
    },

    # ── BÖLÜM 15 ─────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 🔧 Bölüm 15 — Vana Durumu Analizi"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "VALVE_COLS = ['bk_irtibat_valve','fast_dosage_valve','kk_irtibat_valve',\n",
            "              'slow_dosage_valve','kk_dosage_valve','bk_dosage_valve','kk_bk_common_discharge']\n",
            "\n",
            "# Her komut için kaç saniye vanalar açık?\n",
            "valve_by_cmd = []\n",
            "for cmd in sorted(train['commandno'].unique()):\n",
            "    subset = train[train['commandno']==cmd]\n",
            "    row = {'Komut': f'{cmd}-{CMD_NAMES.get(cmd,\"?\")}', 'Satır': len(subset)}\n",
            "    for v in VALVE_COLS:\n",
            "        if v in subset.columns:\n",
            "            pct = (subset[v].astype(str).str.upper() == 'TRUE').mean() * 100\n",
            "            row[v.replace('_valve','').replace('_',' ')] = round(pct, 1)\n",
            "    valve_by_cmd.append(row)\n",
            "\n",
            "valve_df = pd.DataFrame(valve_by_cmd).set_index('Komut')\n",
            "valve_show = valve_df.drop(columns=['Satır'], errors='ignore')\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(14, 5))\n",
            "im = ax.imshow(valve_show.values.astype(float), cmap='YlOrRd', aspect='auto', vmin=0, vmax=100)\n",
            "ax.set_xticks(range(len(valve_show.columns)))\n",
            "ax.set_xticklabels(valve_show.columns, rotation=35, ha='right')\n",
            "ax.set_yticks(range(len(valve_show.index)))\n",
            "ax.set_yticklabels(valve_show.index)\n",
            "plt.colorbar(im, ax=ax, label='Açık Kalma Oranı (%)')\n",
            "for i in range(len(valve_show.index)):\n",
            "    for j in range(len(valve_show.columns)):\n",
            "        val = valve_show.values[i, j]\n",
            "        if not np.isnan(val):\n",
            "            ax.text(j, i, f'{val:.0f}%', ha='center', va='center',\n",
            "                    fontsize=10, color='black' if val < 60 else 'white', fontweight='bold')\n",
            "ax.set_title('Komut × Vana Açık Kalma Oranı (%)', fontweight='bold', fontsize=13)\n",
            "plt.tight_layout()\n",
            "plt.savefig('valve_heatmap.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()\n",
            "print('\\nVana Açık Kalma Oranları (%):')\n",
            "print(valve_df.to_string())"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Vana durumuna göre bk_level değişimi\n",
            "bk_valve = train[train['bk_level'] > 0]\n",
            "\n",
            "fig, axes = plt.subplots(2, 4, figsize=(18, 8))\n",
            "axes = axes.flatten()\n",
            "\n",
            "for i, v in enumerate(VALVE_COLS):\n",
            "    ax = axes[i]\n",
            "    if v not in bk_valve.columns:\n",
            "        ax.set_visible(False); continue\n",
            "    closed = bk_valve[bk_valve[v].astype(str).str.upper() == 'FALSE']['bk_level']\n",
            "    opened = bk_valve[bk_valve[v].astype(str).str.upper() == 'TRUE']['bk_level']\n",
            "    data = [closed.sample(min(5000,len(closed)),random_state=42).values,\n",
            "            opened.sample(min(5000,len(opened)),random_state=42).values]\n",
            "    bp = ax.boxplot(data, labels=['Kapalı','Açık'], patch_artist=True)\n",
            "    bp['boxes'][0].set_facecolor('#AED6F1')\n",
            "    bp['boxes'][1].set_facecolor('#F1948A')\n",
            "    ax.set_title(v.replace('_valve','').replace('_',' '), fontweight='bold', fontsize=9)\n",
            "    ax.set_ylabel('bk_level')\n",
            "\n",
            "axes[-1].set_visible(False)\n",
            "plt.suptitle('Vana Durumu (Açık/Kapalı) → bk_level', fontsize=14, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('valve_vs_bklevel.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()"
        ]
    },

    # ── BÖLÜM 16 ─────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 🎯 Bölüm 16 — bk_target_level vs bk_level (En Güçlü Feature)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# bk_target_level → bk_level en güçlü feature\n",
            "target_subset = train[(train['bk_level'] > 0) & (train['bk_target_level'] > 0)]\n",
            "sample_t = target_subset.sample(min(30000, len(target_subset)), random_state=42)\n",
            "\n",
            "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
            "\n",
            "# Scatter: bk_target_level vs bk_level (komut renkli)\n",
            "for cmd in sorted(sample_t['commandno'].unique()):\n",
            "    chunk = sample_t[sample_t['commandno']==cmd]\n",
            "    axes[0].scatter(chunk['bk_target_level'], chunk['bk_level'],\n",
            "                    alpha=0.2, s=5, label=CMD_NAMES.get(cmd,str(cmd)),\n",
            "                    color=CMD_COLORS.get(cmd,'gray'), rasterized=True)\n",
            "axes[0].plot([0,100],[0,100],'r--', linewidth=1.5, label='y=x')\n",
            "axes[0].set_xlabel('bk_target_level')\n",
            "axes[0].set_ylabel('bk_level')\n",
            "axes[0].set_title('bk_target_level vs bk_level\\n(Komut tiplerine göre)', fontweight='bold')\n",
            "axes[0].legend(markerscale=3, fontsize=8)\n",
            "\n",
            "# Error = bk_level - bk_target_level dağılımı\n",
            "target_subset2 = train[(train['bk_level']>0) & (train['bk_target_level']>0)].copy()\n",
            "target_subset2['error'] = target_subset2['bk_level'] - target_subset2['bk_target_level']\n",
            "for cmd in sorted(target_subset2['commandno'].unique()):\n",
            "    chunk = target_subset2[target_subset2['commandno']==cmd]['error']\n",
            "    chunk = chunk.sample(min(10000, len(chunk)), random_state=42)\n",
            "    axes[1].hist(chunk, bins=60, alpha=0.5, label=CMD_NAMES.get(cmd,str(cmd)),\n",
            "                 color=CMD_COLORS.get(cmd,'gray'), density=True)\n",
            "axes[1].axvline(0, color='red', linestyle='--')\n",
            "axes[1].set_xlabel('bk_level − bk_target_level (hata)')\n",
            "axes[1].set_title('PID Kontrol Hatası Dağılımı\\n(Komut tiplerine göre)', fontweight='bold')\n",
            "axes[1].legend(fontsize=9)\n",
            "\n",
            "# Korelasyon: her komut için bk_target vs bk_level\n",
            "corr_by_cmd = []\n",
            "for cmd in sorted(train['commandno'].unique()):\n",
            "    chunk = train[(train['commandno']==cmd) & (train['bk_level']>0) & (train['bk_target_level']>0)]\n",
            "    if len(chunk) > 100:\n",
            "        c = chunk[['bk_level','bk_target_level']].corr().iloc[0,1]\n",
            "        corr_by_cmd.append({'Komut': CMD_NAMES.get(cmd,str(cmd)), 'Korelasyon': round(c,4)})\n",
            "corr_cmd_df = pd.DataFrame(corr_by_cmd)\n",
            "axes[2].barh(corr_cmd_df['Komut'], corr_cmd_df['Korelasyon'],\n",
            "             color=[CMD_COLORS.get(k,'gray') for k in sorted(train['commandno'].unique())], alpha=0.85)\n",
            "axes[2].set_xlim(0,1)\n",
            "axes[2].axvline(0.9, color='red', linestyle='--', label='0.90')\n",
            "axes[2].set_title('Komut Tipi × bk_target_level\\n→ bk_level Korelasyonu', fontweight='bold')\n",
            "axes[2].set_xlabel('Pearson r')\n",
            "axes[2].legend()\n",
            "for i, row in corr_cmd_df.iterrows():\n",
            "    axes[2].text(row['Korelasyon']+0.01, i, f'{row[\"Korelasyon\"]:.4f}', va='center', fontsize=10)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig('target_level_analysis.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()"
        ]
    },

    # ── BÖLÜM 17 ─────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## ⚡ Bölüm 17 — Feature Engineering Önerileri (Leakage-Free)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Proses içi göreceli zaman özelliklerini hesapla ve etkisini göster\n",
            "train['elapsed_sec']  = (train['ts'] - train['starttime']).dt.total_seconds().clip(0)\n",
            "train['remaining_sec'] = (train['endtime'] - train['ts']).dt.total_seconds().clip(0)\n",
            "train['proc_dur2']     = (train['endtime'] - train['starttime']).dt.total_seconds()\n",
            "train['elapsed_pct']   = (train['elapsed_sec'] / train['proc_dur2'].replace(0,np.nan) * 100).clip(0,100)\n",
            "\n",
            "# Bu featureların bk_level ile korelasyonu\n",
            "new_feats = ['elapsed_sec','remaining_sec','elapsed_pct','rel_time','proc_dur']\n",
            "existing_feats = ['bk_target_level','kk_level','ak_level','fabric_weight']\n",
            "all_feats = [f for f in new_feats + existing_feats if f in train.columns]\n",
            "\n",
            "feat_corr = []\n",
            "for f in all_feats:\n",
            "    for cmd in [None, 19, 20, 21, 22]:\n",
            "        if cmd is None:\n",
            "            subset = train[train['bk_level'] > 0]\n",
            "            label = 'Tüm Komutlar'\n",
            "        else:\n",
            "            subset = train[(train['commandno']==cmd) & (train['bk_level']>0)]\n",
            "            label = CMD_NAMES.get(cmd, str(cmd))\n",
            "        if f not in subset.columns or len(subset) < 100:\n",
            "            continue\n",
            "        valid = subset[[f,'bk_level']].dropna()\n",
            "        if len(valid) < 100 or valid[f].std() == 0:\n",
            "            continue\n",
            "        c = valid.corr().iloc[0,1]\n",
            "        feat_corr.append({'Feature': f, 'Komut': label, 'Korelasyon': round(c, 4)})\n",
            "\n",
            "corr_tbl = pd.DataFrame(feat_corr).pivot(index='Feature', columns='Komut', values='Korelasyon')\n",
            "print('=== Feature → bk_level Korelasyonu (Komut Tiplerine Göre) ===')\n",
            "print(corr_tbl.round(4).to_string())\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(14, 6))\n",
            "im = ax.imshow(corr_tbl.values.astype(float), cmap='RdYlGn', aspect='auto', vmin=-1, vmax=1)\n",
            "ax.set_xticks(range(len(corr_tbl.columns)))\n",
            "ax.set_xticklabels(corr_tbl.columns, rotation=30, ha='right')\n",
            "ax.set_yticks(range(len(corr_tbl.index)))\n",
            "ax.set_yticklabels(corr_tbl.index)\n",
            "plt.colorbar(im, ax=ax, label='Pearson r')\n",
            "for i in range(len(corr_tbl.index)):\n",
            "    for j in range(len(corr_tbl.columns)):\n",
            "        val = corr_tbl.values[i, j]\n",
            "        if not np.isnan(val):\n",
            "            ax.text(j, i, f'{val:.2f}', ha='center', va='center',\n",
            "                    fontsize=9, color='black' if abs(val) < 0.7 else 'white', fontweight='bold')\n",
            "ax.set_title('Feature × bk_level Korelasyon Haritası\\n(Leakage-free featurelar dahil)', fontsize=13, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('feature_importance_heatmap.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─── Önerilen Feature Listesi ────────────────────────────────\n",
            "print(\"\"\"\n",
            "╔══════════════════════════════════════════════════════════════════╗\n",
            "║           🚀 ÖNERİLEN FEATURE MÜHENDİSLİĞİ PLANI              ║\n",
            "╠══════════════════════════════════════════════════════════════════╣\n",
            "║  [ZAMAN ÖZELLİKLERİ — Leakage-free]                           ║\n",
            "║    elapsed_sec   : Proses başından geçen süre (sn)             ║\n",
            "║    remaining_sec : Proses bitimine kalan süre (sn)             ║\n",
            "║    elapsed_pct   : Proses içi ilerleme yüzdesi (%)             ║\n",
            "║    proc_dur      : Toplam proses süresi (sn)                   ║\n",
            "║                                                                  ║\n",
            "║  [KOMUT ÖZELLİKLERİ]                                           ║\n",
            "║    is_transfer   : Komut 19/20 = 1, Komut 21/22 = 0            ║\n",
            "║    is_bk_cmd     : Komut 20/22 = 1 (BK kaynaklı), 19/21 = 0   ║\n",
            "║    commandno_enc : Label encoding veya one-hot                  ║\n",
            "║                                                                  ║\n",
            "║  [HEDEF İLE İLGİLİ — Leakage-free]                            ║\n",
            "║    bk_target_level ★ : Dozaj hedefi — en güçlü feature        ║\n",
            "║    pid_error       : bk_level - bk_target_level (SADECE TRAIN) ║\n",
            "║    target_diff     : bk_target - mevcut tahmin (autoregressive) ║\n",
            "║                                                                  ║\n",
            "║  [VANA KOMBİNASYONLARI]                                        ║\n",
            "║    n_valves_open   : Aynı anda açık vana sayısı                ║\n",
            "║    bk_fully_open   : bk_irtibat & fast_dosage aynı anda açık?  ║\n",
            "║                                                                  ║\n",
            "║  [DİĞER SENSORLER]                                             ║\n",
            "║    kk_level        : KK seviyesi                               ║\n",
            "║    ak_level        : Ana kazan seviyesi (litre)                ║\n",
            "║    fabric_weight   : Kumaş ağırlığı                            ║\n",
            "║    kk_mikser_robotu: Salınım yapıcı                             ║\n",
            "║    bk_mikser_robotu: Salınım yapıcı                             ║\n",
            "║                                                                  ║\n",
            "║  [⚠️ DATA LEAKAGE RISKI — KULLANMA!]                          ║\n",
            "║    bk_lag1         : Bir önceki saniyenin bk_level değeri       ║\n",
            "║    bk_rolling_mean : Kayan ortalama                             ║\n",
            "╚══════════════════════════════════════════════════════════════════╝\n",
            "\"\"\")"
        ]
    },

    # ── BÖLÜM 18 ─────────────────────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 🔬 Bölüm 18 — Örnek Proses Görselleştirmesi (Tek Batch)"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Her komut tipinden bir örnek proses seç ve görselleştir\n",
            "fig, axes = plt.subplots(2, 2, figsize=(18, 10))\n",
            "axes = axes.flatten()\n",
            "\n",
            "for i, cmd in enumerate(sorted(train['commandno'].unique())):\n",
            "    ax = axes[i]\n",
            "    # Bu komut tipinden rastgele bir batch seç\n",
            "    batches = train[train['commandno']==cmd]['batchkey'].unique()\n",
            "    np.random.seed(42+cmd)\n",
            "    batch = np.random.choice(batches)\n",
            "    proc = train[(train['batchkey']==batch) & (train['commandno']==cmd)].sort_values('ts')\n",
            "\n",
            "    ax2 = ax.twinx()\n",
            "    ax.plot(proc['ts'], proc['bk_level'], color=CMD_COLORS.get(cmd,'gray'),\n",
            "            linewidth=2, label='bk_level', zorder=3)\n",
            "    if 'bk_target_level' in proc.columns and proc['bk_target_level'].sum() > 0:\n",
            "        ax.plot(proc['ts'], proc['bk_target_level'], 'k--',\n",
            "                linewidth=1.5, label='bk_target_level', alpha=0.7)\n",
            "    # Vana durumlarını arka planda göster\n",
            "    for v, vc in zip(['fast_dosage_valve','slow_dosage_valve'],['#AED6F1','#FADBD8']):\n",
            "        if v in proc.columns:\n",
            "            proc[v+'_num'] = proc[v].astype(str).str.upper().map({'TRUE':1,'FALSE':0}).fillna(0)\n",
            "            ax2.fill_between(proc['ts'], proc[v+'_num'], alpha=0.15, color=vc, label=v.replace('_valve',''))\n",
            "    ax.set_title(f'Komut {cmd} — {CMD_NAMES.get(cmd,\"?\")}\\nBatch: {batch}', fontweight='bold')\n",
            "    ax.set_ylabel('Seviye (%)')\n",
            "    ax2.set_ylabel('Vana (0/1)', alpha=0.5)\n",
            "    ax2.set_ylim(-0.1, 3)\n",
            "    ax.legend(loc='upper right', fontsize=8)\n",
            "    ax2.legend(loc='upper left', fontsize=7)\n",
            "    ax.grid(alpha=0.3)\n",
            "    ax.tick_params(axis='x', rotation=30)\n",
            "\n",
            "plt.suptitle('Komut Tiplerine Göre Örnek Proses (bk_level + Vanalar)', fontsize=14, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.savefig('sample_processes.png', dpi=120, bbox_inches='tight')\n",
            "plt.show()"
        ]
    },

    # ── BÖLÜM 19 — FINAL RAPOR ───────────────────────────────
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": ["## 📋 Bölüm 19 — Yarışma Strateji Özeti"]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# bk_level = 0 satırlarının oranı\n",
            "zero_pct = (train['bk_level'] == 0).mean() * 100\n",
            "nonzero_cnt = (train['bk_level'] > 0).sum()\n",
            "print(f'\\nbk_level = 0 satır oranı : {zero_pct:.2f}% (değerlendirme dışı!)')\n",
            "print(f'bk_level > 0 satır sayısı: {nonzero_cnt:,} (bunlar puanlanacak!)')\n",
            "\n",
            "# Transfer vs Dozaj satır oranları\n",
            "transfer_cnt = train[train['commandno'].isin([19,20])].shape[0]\n",
            "dozaj_cnt    = train[train['commandno'].isin([21,22])].shape[0]\n",
            "print(f'\\nTransfer satırları (19,20): {transfer_cnt:,} ({transfer_cnt/len(train)*100:.1f}%)')\n",
            "print(f'Dozaj satırları (21,22)   : {dozaj_cnt:,} ({dozaj_cnt/len(train)*100:.1f}%)')\n",
            "\n",
            "print(\"\"\"\n",
            "╔══════════════════════════════════════════════════════════╗\n",
            "║              🏆 YARIŞ STRATEJİSİ                        ║\n",
            "╠══════════════════════════════════════════════════════════╣\n",
            "║  1. Transfer (19,20) ve Dozaj (21,22) için               ║\n",
            "║     AYRI modeller eğit — davranışlar çok farklı!        ║\n",
            "║                                                          ║\n",
            "║  2. bk_target_level ★ en güçlü feature — kesinlikle     ║\n",
            "║     modele dahil et                                      ║\n",
            "║                                                          ║\n",
            "║  3. elapsed_pct (proses içi ilerleme) ekle —             ║\n",
            "║     leakage-free ve çok informatif                       ║\n",
            "║                                                          ║\n",
            "║  4. Autoregressive tahmin: test'te bir önceki            ║\n",
            "║     tahmini lag feature olarak kullan (sıralı predict)  ║\n",
            "║                                                          ║\n",
            "║  5. bk_level=0 satırları için 0.0 yaz, puanlanmaz        ║\n",
            "║                                                          ║\n",
            "║  6. Makine 243 için komut 20 yoktur — model için         ║\n",
            "║     dikkat et                                            ║\n",
            "╚══════════════════════════════════════════════════════════╝\n",
            "\"\"\")"
        ]
    }
]

# Mevcut hücrelere ekle
nb['cells'].extend(new_cells)

with open('eda_analysis.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f'✅ {len(new_cells)} yeni hücre eklendi!')
